[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "src/app",
    "src/common",
    "src/storage"
]

[workspace.dependencies]
datafusion = "54.1.0"
datafusion-cli = "54.1.0"
sqlparser = "0.62.0"
arrow-flight = { version = "58.4.0", features = ["flight-sql"] }
tonic = "0.14"
prost = "0.14"
tokio = { version = "1.0", features = ["rt-multi-thread", "tracing", "rt", "signal"] }
console-subscriber = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
typetag = "0.2"
toml = "0.9.5"
futures = "0.3.31"
async-trait = "0.1.88"
bytes = "1"
url = "2.5.7"
percent-encoding = "2.3"
iceberg = { git = "https://github.com/apache/iceberg-rust", rev = "d05d56645979804c659aa265f6041d93ea0e6557" }
iceberg-datafusion = { git = "https://github.com/apache/iceberg-rust", rev = "d05d56645979804c659aa265f6041d93ea0e6557" }
opendal = { version = "0.58.1", features = ["services-s3", "services-oss", "services-hdfs-native"] }
object_store_opendal = "0.58.0"
deltalake = { git = "https://github.com/delta-io/delta.rs", rev = "84fad0b1bd861367a94e144cd253323559c9d3bd", features = ["datafusion"] }
paimon = { version = "0.3.0", features = ["storage-s3", "storage-oss", "storage-hdfs"] }
paimon-datafusion = "0.3.0"
mimalloc = { version = "0.1", default-features = false }
lakelet-app = { path = "src/app" }
lakelet-storage = {path = "src/storage"}
lakelet-common = {path = "src/common"}

[profile.release]
lto = true
codegen-units = 1
