[package]
name = "lakelet-storage"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
datafusion = { workspace = true }
url = { workspace = true }
iceberg = { workspace = true }
deltalake = { workspace = true }
toml = { workspace = true }
hdfs-native-object-store = { workspace = true }
